version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: 4320_Final_project
    container_name: 4320FinalProject
    ports:
      -"5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"